version: "3.7"

services:
  bazarr:
    container_name: bazarr
    image: ghcr.io/hotio/bazarr
    ports:
      - "6767:6767"
    environment:
      - PUID=1003
      - PGID=1003
      - UMASK=002
      - TZ=America/Denver
    volumes:
      - /mnt/SASma/Config/bazarr:/config
      - /mnt/SASma/Media/Movies:/movies #optional
      - /mnt/SASma/Media/Shows:/shows
      - /mnt/SASma/Media/Anime:/anime #optional
    restart: unless-stopped
    privileged: true