 #reboot-truenas.yml
- debug:
    msg: "Booting TN"
- name: Boot TN
  become: true
  become_method: sudo
  run_once: true
  delegate_to: "{{ your_proxmox_host }}"
  shell: |
    sudo /usr/sbin/qm start {{ TrueNAS_ID }}
  when: false

- debug:
    msg: "rebooted TN"

- debug:
    msg: "Pinging Until Ready TN"

- name: Wait for TrueNAS to become reachable
  delegate_to: localhost
  run_once: true
  block:
    - name: ICMP ping from Control Node to Remote Node
      command: ping -c 2 "{{ TrueNAS_IP }}"
      ignore_unreachable: true
      ignore_errors: yes
      changed_when: false 
      check_mode: false
      register: router_ping
    - name: Check if TrueNAS is running
      set_fact:
        truenas_reachable: "{{ router_ping.rc == 0 }}"
  until: truenas_reachable
  retries: 10
  delay: 10

- debug:
    msg: "Success! Waiting 20sec"

- name: Pause to allow time for TrueNAS to boot
  pause:
    seconds: 20  # Adjust the value as needed to wait for TrueNAS to boot (e.g., 5 minutes)

- debug:
    msg: "Success! Mounting All"

- name: Execute mount -a command with sudo on all hosts in the group
  become: true
  become_method: sudo
  delegate_to: "{{ item }}"
  ansible.builtin.shell: sudo mount -a
  loop: "{{ groups['SMB'] }}"
  loop_control:
        label: "{{ item }}"