# reboot-truenas.yml
#- name: Send shell command for failed VMs
#  become: true
#  become_method: sudo
#  delegate_to: "{{ your_proxmox_host }}"
#  shell: |
#    sudo /usr/sbin/qm start {{ TrueNAS_ID }}

- name: Execute mount -a command with sudo on all hosts in the group
  become: true
  become_method: sudo
  delegate_to: "{{ ansible_host }}"
  ansible.builtin.shell: sudo mount -a
  loop: "{{ groups['SMB'] }}"