mqtt:
  host: a0d7b954-emqx
  user: frigate
  password: j@cob1113

detectors:
  cpu:
    type: cpu
    num_threads: 8

cameras:
  front_823a: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://zoneminder:69zoneminder420@10.10.4.60:554//h264Preview_01_sub # <----- The stream you want to use for detection
          roles:
            - detect
            - rtmp
        - path: rtsp://zoneminder:69zoneminder420@10.10.4.60:554//h265Preview_01_main # <----- The stream you want to use for recording
          roles:
            - record
    rtmp:
      enabled: True
    record:
      enabled: True
    snapshots:
      enabled: True
    detect:
      enabled: False # <---- disable detection until you have a working camera feed
      width: 640 # <---- update for your camera's resolution
      height: 360 # <---- update for your camera's resolution
      fps: 10
    objects:
      track:
        - person
        - car
  