---
version: "2.1"
services:
  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing_extenal
    hostname: syncthing_extenal #optional
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/Denver
    volumes:
      - /mnt/SASma/Config/syncthing_extenal:/config
      - /mnt/important:/SAS
      - /mnt/external/ImportantFiles:/external
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped