rtmp://zoneminder:69zoneminder420@10.10.4.60/bcs/channel0_main.bcs?token=sdasdasd&channel=0&stream=0&user=zoneminder&password=69zoneminder420

zoneminder
69zoneminder420

works!:
rtsp://zoneminder:69zoneminder420@10.10.4.60:554//h264Preview_01_sub

rtsp://zoneminder:69zoneminder420@10.10.4.60:554//h265Preview_01_main