---
version: '3'

services:
  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=America/Denver
      - PORT=5055 #optional
    ports:
      - 5055:5055
    volumes:
      - /mnt/Config/Overseer:/app/config
    restart: unless-stopped