version: "3"
services:
  vpn:
    image: azinchen/nordvpn:latest
    cap_add:
      - net_admin
    devices:
      - /dev/net/tun
    environment:
      - USER=y2rmXpqfhxSqgF9D6WJy47Q1
      - PASS=97PJLjEGkFLB8dPRLDiV1tsQ
      - COUNTRY=United States
      - GROUP=Standard VPN servers
      - RANDOM_TOP=10
      - RECREATE_VPN_CRON=5 */3 * * *
      - NETWORK=192.168.1.0/24;192.168.2.0/24
      - OPENVPN_OPTS=--mute-replay-warnings
    ports:
      - 5050:50
    restart: unless-stopped
  
  web:
    image: nginx
    network_mode: service:vpn